apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-node-chrome
  labels:
    app: selenium-node-chrome
spec:
  replicas: {{ .Values.images.nodes.chrome.replicas | default 1 }}
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: {{ .Chart.Name }}-node-chrome
        image: {{ printf "%s:%s" .Values.images.nodes.chrome.repository .Values.images.nodes.chrome.tag }}
        imagePullPolicy: {{ .Values.images.nodes.chrome.pullPolicy }}
        ports:
          - containerPort: 5555
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: HUB_HOST
            value: "{{ .Chart.Name }}-hub"
          - name: HUB_PORT
            value: "4444"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
