apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: {{ .Chart.Name }}-hub
        image: {{ printf "%s:%s" .Values.images.seleniumHub.repository .Values.images.seleniumHub.tag }}
        imagePullPolicy: {{ .Values.images.seleniumHub.pullPolicy }}
        ports:
          - containerPort: 4444
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
